/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowj1 (void);
GtkWidget* create_windowj2 (void);
GtkWidget* create_windowj3 (void);
GtkWidget* create_windowj4 (void);
GtkWidget* create_windowj5 (void);
GtkWidget* create_windowj6 (void);
GtkWidget* create_windowj7 (void);
GtkWidget* create_windowj0 (void);
GtkWidget* create_windowj11 (void);
