/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowj1,*windowj2,*windowj3,*windowj4,*windowj5,*windowj6,*windowj7,*windowj0,*windowj11;
  

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowj1 = create_windowj1 ();
  gtk_widget_show (windowj1);
 
 /* windowj2 = create_windowj2();
  gtk_widget_show (windowj2);
  windowj3 =create_windowj3 ();
  gtk_widget_show (windowj3);
  windowj4 = create_windowj4();
  gtk_widget_show (windowj4);
  windowj4 = create_windowj5();
  gtk_widget_show (windowj5);
  windowj6 = create_windowj6();
  gtk_widget_show (windowj6);
  windowj7 = create_windowj7();
  gtk_widget_show (windowj7);
   windowj0 =create_windowj0 ();
  gtk_widget_show (windowj0);*/
  windowj11 = create_windowj11();
  gtk_widget_show (windowj11);
  
gtk_main ();
  return 0;
}

